import torch
import math
from typing import Optional

# Import the compiled CUDA/C++ extension.
# Prefer `quest._kernels` (package-local), but fall back to a top-level
# `_kernels` if it is available.
try:
    import quest._kernels as _kernels  # type: ignore[attr-defined]
except ModuleNotFoundError:
    import _kernels as _kernels  # type: ignore[assignment]

# Local helpers (relative imports within this package)
from .utils import TensorLayout
from .kv_cache import KvCache
from .controller import InferenceController
from .decode_wrapper import BatchDecodeWithPagedKVCacheWrapper

__all__ = [
    'TensorLayout',
    'KvCache',
    'InferenceController',
    "BatchDecodeWithPagedKVCacheWrapper",
    "append_kv",
    "prefill_forward",
    "decode_estimate",
    "decode_topk",
    "decode_sparse_attn",
    "rms_norm_forward",
    "apply_rope_in_place",
]

def apply_rope_in_place(
    q: torch.Tensor,
    k: torch.Tensor,
    past_kv_len: int,
    rope_scale: Optional[float] = None,
    rope_theta: Optional[float] = None,
):
    """
    Semantics of `apply_rope_in_place`:
    Apply RoPE (Relative Positional Encoding) in-place.
    On q, k which is generated by GEMM. Layout is naturally NHD.

    Args:
        q: Shape: `[N, H, D]`.
        k: Shape: `[N, H, D]`. 
        past_kv_len: Length of past KV cache. Used to calculate frequency.
    """
    if rope_scale is None:
        rope_scale = 1.0
    if rope_theta is None:
        rope_theta = 1e4
    # The custom CUDA kernel expects contiguous tensors; some upstream ops
    # (e.g., view/transpose/reshape in attention) may produce non-contiguous
    # layouts, so we enforce contiguity here.
    q_contig = q.contiguous()
    k_contig = k.contiguous()
    _kernels.apply_rope_in_place(
        q_contig,
        k_contig,
        past_kv_len,
        rope_scale,
        rope_theta,
    )

def rms_norm_forward(
    input: torch.Tensor,
    weight: torch.Tensor,
    epsilon: float,
) -> torch.Tensor:
    o = torch.empty_like(input, dtype=input.dtype, device=input.device)
    f = _kernels.rms_norm_forward
    f(
        input,
        weight,
        o,
        epsilon,
    )
    return o

def append_kv(
    k: torch.Tensor,
    v: torch.Tensor,
    iController: InferenceController,
    layer_idx: int,
):
    """
    Semantics of `append_kv`:
    Append new generated k/v into kv cache and meta data cache.
    Automatically dispatch to Prefill / Decode Kernel

    Notations for shapes:
    `B`: batch size
    `N`: number of heads
    `D`: head dimension
    `L`: number of layers
    `MAXLEN`: maximum length of the KV cache

    Args:
        k: Shape: `[B, N, D]`. Key projection (`X @ W_k`).
        v: Shape: `[B, N, D]`. Value projection (`X @ W_v`).
        iController: InferenceController object, which contains all needed information.
        layer_idx: Layer index of the KV cache.
    """
    # Custom CUDA kernels expect contiguous tensors; upstream projections and
    # reshapes may produce non-contiguous views, so enforce contiguity here.
    k = k.contiguous()
    v = v.contiguous()

    seq_len = k.size(0)
    if seq_len > 1:
        _kernels.append_kv_cache_prefill(
            k,
            v,
            iController.kv_cache.buf_layer(layer_idx),
            iController.kv_indices_with_last,
            iController.kv_indptr_for_append,
            iController.kv_cache.last_page_len,
            iController.kv_last_page_idx,
            iController.metadata_cache.buf_layer(layer_idx),
            iController.metadata_indices,
            iController.metadata_indptr_for_append,
            iController.metadata_cache.last_page_len,
            iController.metadata_last_page_idx,
            iController.layout
        )
    else:
        _kernels.append_kv_cache_decode(
            k,
            v,
            iController.kv_cache.buf_layer(layer_idx),
            iController.kv_indices_with_last,
            iController.kv_indptr_for_append,
            iController.kv_cache.last_page_len,
            iController.kv_last_page_idx,
            iController.metadata_cache.buf_layer(layer_idx),
            iController.metadata_indices,
            iController.metadata_indptr_for_append,
            iController.metadata_cache.last_page_len,
            iController.metadata_last_page_idx,
            iController.layout
        )

def prefill_forward(
    q: torch.Tensor,
    iController: InferenceController,
    layer_idx: int,
    rope_scale: Optional[float] = None,
    rope_theta: Optional[float] = None,
) -> torch.Tensor:
    """
    Semantics of `prefill_forward`:
    New genrated K/Vs are already in the kv cache and meta data cache (well-maintained).
    Perform FlashInfer Self-Attention with Casual Attention.
    Note that we not have position shift and current version not support Prefill Optimization.

    Notations for shapes:
    `B`: batch size
    `N`: number of heads
    `D`: head dimension
    `L`: number of layers
    `MAXLEN`: maximum length of the KV cache

    Args:
        q: Shape: `[B, N, D]`. Key projection (`X @ W_k`).
        iController: InferenceController object, which contains all needed information.
        layer_idx: Layer index of the KV cache.
    """
    if rope_scale is None:
        rope_scale = 1.0
    if rope_theta is None:
        rope_theta = 1e4

    # Ensure q is contiguous for the custom kernel.
    q = q.contiguous()

    f = _kernels.prefill_with_paged_kv_cache
    o = f(
        q,
        iController.kv_cache.buf_layer(layer_idx),
        iController.kv_indices_with_last,
        iController.kv_cache.last_page_len,
        True, # Casual
        iController.layout,
        False, # FP16 Accumulator for 4090
        rope_scale,
        rope_theta,
    )
    return o

def decode_estimate(
    q: torch.Tensor,
    iController: InferenceController,
    layer_idx: int,
) -> torch.Tensor:
    """
    Semantics of `decode_estimate`:
    When decoding, estimate the attention score for each page.

    Notations for shapes:
    `B`: batch size
    `N`: number of heads
    `D`: head dimension
    `L`: number of layers
    `MAXLEN`: maximum length of the KV cache

    Args:
        q: Shape: `[B, N, D]`. Key projection (`X @ W_k`).
        iController: InferenceController object, which contains all needed information.
        layer_idx: Layer index of the KV cache.
    """
    f = _kernels.estimate_attn_score
    # (iController.metadata_cache.seqlen - 1) is manually excluding the last elements, which is the current page.
    o = torch.empty((iController.num_heads, iController.metadata_cache.seqlen - 1), dtype=q.dtype, device=q.device)

    # Ensure q and metadata indices/indptr are contiguous for the kernel.
    q = q.contiguous()
    metadata_buf = iController.metadata_cache.buf_layer(layer_idx)
    metadata_indices = iController.metadata_indices.contiguous() if iController.metadata_indices is not None else None
    metadata_indptr = iController.metadata_indptr_for_append.contiguous() if iController.metadata_indptr_for_append is not None else None

    f(
        q,
        o,
        metadata_buf,
        metadata_indices,
        metadata_indptr,
        iController.metadata_cache.last_page_len, # One entry delta is considered by kernel-level implementation
        iController.metadata_last_page_idx,
        iController.layout,
    )
    return o

def decode_topk(
    estimated_attn_score: torch.Tensor,
    iController: InferenceController,
):
    """
    Semantics of `decode_topk`:
    select top-k pages with highest attention score.

    Notations for shapes:
    `B`: batch size
    `N`: number of heads
    `D`: head dimension
    `L`: number of layers
    `MAXLEN`: maximum length of the KV cache

    Args:
        q: Shape: `[B, N, D]`. Key projection (`X @ W_k`).
        iController: InferenceController object, which contains all needed information.
        layer_idx: Layer index of the KV cache.
    """
    # excluding the last page
    page_budget = iController.inference_page_budget - 1
    if page_budget <= 0:
        return

    # estimated_attn_score: [num_heads, num_pages_without_last]
    # kv_indices_without_last: [num_heads, num_pages_without_last] (int32)
    num_heads, num_pages = estimated_attn_score.shape
    k = min(page_budget, num_pages)

    # Top-k scores per head
    topk_vals, topk_pos = torch.topk(
        estimated_attn_score,
        k=k,
        dim=1,
        largest=True,
        sorted=True,
    )  # both [H, k]

    # Map local positions -> page ids via kv_indices_without_last
    kv_idx_long = iController.kv_indices_without_last.to(dtype=torch.long)
    topk_pages_long = torch.gather(kv_idx_long, 1, topk_pos)

    # Write into controller buffers (they are preallocated)
    iController.topk_dout_buffer[:, :k] = topk_vals
    iController.topk_dindices_buffer[:, :k] = topk_pages_long.to(dtype=torch.int32)

def decode_sparse_attn(
    q: torch.Tensor,
    iController: InferenceController,
    layer_idx: int,
    topk_indices: torch.Tensor,
    rope_scale: Optional[float] = None,
    rope_theta: Optional[float] = None,
) -> torch.Tensor:
    """
    Semantics of `decode_sparse_attn`:
    Excute self-attention only on the selected pages (Top-k output)

    Notations for shapes:
    `B`: batch size
    `N`: number of heads
    `D`: head dimension
    `L`: number of layers
    `MAXLEN`: maximum length of the KV cache

    Args:
        q: Shape: `[B, N, D]`. Key projection (`X @ W_k`).
        iController: InferenceController object, which contains all needed information.
        layer_idx: Layer index of the KV cache.
        topk_indices: Shape: `[N, page_budget-1]`. Top-k indices.
    """
    # Ensure q and topk_indices are contiguous for the decode kernel.
    q = q.contiguous()
    topk_indices = topk_indices.contiguous()

    o = torch.empty_like(q, dtype=q.dtype, device=q.device)
    iController._decode_handler.forward(
        q,
        o,
        iController.kv_cache.buf_layer(layer_idx),
        topk_indices,
        iController.kv_indptr_for_approx_decode,
        iController.kv_cache.last_page_len,
        iController.kv_last_page_idx,
        rope_scale,
        rope_theta,
    )
    return o
